### PR TITLE
Fixed the code of 01_doubly_linked_list.c

### LINKED ISSUE #1: Test
talk less show me your code

### PR DESCRIPTION
**Pull request by rajeshkumar2024**
@yashrajyash Please Merge this PR. I have fixed the code.

Fixed #1

### CODE REVIEW

File: 02_Doubly_Linked_List/01_doubly_linked_list.c [hunk 1]
```diff
@@ -1,3 +1,4 @@
+//Fixed some lines in the code
```
Comment (yashrajyash) [inline 02_Doubly_Linked_List/01_doubly_linked_list.c:1]:
```suggestion
//Fixed many lines in the program
```

**Review by yashrajyash — APPROVED** [review]
Great work!
